os:
  editPreset: "nvim"

customCommands:
  - key: "<c-p>"
    command: "git remote prune {{.SelectedRemote.Name}}"
    context: "remotes"
    loadingText: "Pruning..."
    description: "Prune deleted remote branches"
  - key: "<c-y>"
    command: "wl-copy --paste-once '{{.SelectedWorktree.Path}}'"
    context: "worktrees"
    loadingText: "Coppied to clipboard"
    output: "none"
    description: "Copy worktree path to clipboard"
